- name: Install runc and CNI plugins on all Kubernetes nodes
  hosts: all
  become: yes
  tasks:
    - name: Download and install runc
      shell: |
        curl -LO https://github.com/opencontainers/runc/releases/download/v1.3.1/runc.amd64
        install -m 755 runc.amd64 /usr/local/sbin/runc

    - name: Download and extract CNI plugins
      shell: |
        curl -LO https://github.com/containernetworking/plugins/releases/download/v1.8.0/cni-plugins-linux-amd64-v1.8.0.tgz
        mkdir -p /opt/cni/bin
        tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.8.0.tgz
