# 192.168.0.0/16 is the CIDR for Calico
- hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes master
      command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_default_ipv4.address }}
        --pod-network-cidr=192.168.0.0/16
        --node-name master
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Prepare kubeconfig for ubuntu user
      become_user: ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: "0755"

    - name: Copy admin.conf to kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: "0644"
        remote_src: yes

    - name: Install operator CRDs
      become_user: ubuntu
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/operator-crds.yaml

    - name: Install Calico operator
      become_user: ubuntu
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/tigera-operator.yaml

    - name: Install Calico custom resources
      become_user: ubuntu
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/custom-resources.yaml

    - name: Generate kubeadm join command
      command: kubeadm token create --print-join-command
      register: kubeadm_join

- hosts: workers
  become: yes
  tasks:
    - name: Join worker nodes to the cluster
      command: "{{ hostvars[groups['master'][0]].kubeadm_join.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
