---
- name: Forwarding IPv4 and letting iptables see bridged traffic
  hosts: all
  become: yes
  tasks:
    - name: Create k8s modules-load file
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"

    - name: modprobe overlay module
      command: modprobe overlay

    - name: modprobe br_netfilter module
      command: modprobe br_netfilter

    - name: Set sysctl params for k8s networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        owner: root
        group: root
        mode: "0644"

    - name: Apply sysctl params without reboot
      command: sysctl --system
